### ISSUE TITLE
how to use?

### ISSUE THREAD

**Issue by henjue** [JetBrains/JetBrains.EnvDTE#4]
how to use? 
i try it,but not offline install!

**Comment by kirillgla** [comment]
Thank you for your interest in this library!
Unfortunately, the library is still under development and is not currently ready for public use.
Once it is available, I intend to integrate it in Rider, so it would be available out-of-the-box.
Could you, please, clarify how you intended to use this library?

**Comment by henjue** [comment]
Because my project uses envdte, but I don't like vs. I like the ide of JetBrains series

**Comment by kirillgla** [comment]
Glad to hear you like our IDEs! 😄
It would help a lot if you told me how exactly your project uses this library. Is it used to generate text/code with [T4](https://docs.microsoft.com/en-us/visualstudio/modeling/code-generation-and-t4-text-templates?view=vs-2019), or is it used somewhere in WinForms designer, or is that library used by the project code itself and loaded into its runtime, or is it used in some other way?

**Comment by kirillgla** [comment]
Starting with Rider 2021.2, this library will be bundled with JetBrains Rider, so there will be no need to install this manually. It will be accessible in T4 templates
